export const APPLICATION_ENV_PROPERTIES = {
    APP_ENV: "MS_TEAMS_WEBHOOK_APP_ENV",
    APP_HTTPS_REQUIRED: "MS_TEAMS_WEBHOOK_APP_HTTPS_REQUIRED",
    APP_HTTPS_KEY_PATH: "MS_TEAMS_WEBHOOK_APP_HTTPS_KEY_PATH",
    APP_HTTPS_CERT_PATH: "MS_TEAMS_WEBHOOK_APP_HTTPS_CERT_PATH",
    APP_PORT: "MS_TEAMS_WEBHOOK_APP_PORT",
    APP_HEADER_AUTHORIZATION_TOKEN_SECRET: "MS_TEAMS_WEBHOOK_APP_HEADER_AUTHORIZATION_TOKEN_SECRET",
};
